version: '3.7'
services:
  app:
    image: myapp
    container_name: myapp
    build: .
    environment:
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_IP=${MYSQL_IP}
    - MYSQL_DB=${MYSQL_DB}
    - MYSQL_KEY=${MYSQL_KEY}
    - AWS_XRAY_DAEMON_ADDRESS=x-ray:2000

  nginx:
    image: nginx
    container_name: nginx
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx.conf
      target: /etc/nginx/nginx.conf

  x-ray:
    container_name: x-ray
    image: amazon/aws-xray-daemon:latest
    ports:
    - "0:2000/udp"
